service:
  name: parse-s3-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: 'eu-central-1'
  environment:
    S3_BUCKET: execution-s3-bucket
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource:
        - 'arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*'
    - Effect: Allow
      Action:
        - "sns:*"
      Resource:
        - 'arn:aws:sns:eu-central-1:307905271295:ProductTopic'

functions:
  s3handler:
    handler: handler.s3handler
    events:
      - s3:
          bucket: ${self:provider.environment.S3_BUCKET}
          event: s3:ObjectCreated:*
          existing: true
